### ISSUE TITLE
Better Docs

### ISSUE THREAD

**Issue by vincentfiestada** [vincentfiestada/acrylic#23]
Currently, docs use MDX which has poor language support and does not allow enough flexibility when it comes to layout and syntax highlighting.

Documentation should have the following features:
* [x] Syntax Highlighting
* [x] Written in a well-supported language
* [x] Live component rendering without duplicated code
* [x] Display prop types
